import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import Layout from '@/components/Layout'
import profilePic from '../../public/images/profile/animetedpics.png'
import AnimatedText from '@/components/AnimatedText'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import lightbulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from '@/components/TransitionEffect'
import ContactForm from '@/components/ContactUs'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Renu&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className='flex items-center text-dark w-full min-h-screen bg-gray-100'>
        <Layout className='pt-0 md:p-16 sm:px-4'>
          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-1/2 md:w-full md:pt-0 sm:pt-0 sm:w-full xs:w-full'>
   <Image
                src={profilePic}
                alt="deshmukhrenu"
                className="w-full h-auto object-contain md:inline-block md:w-full sm:max-h-[50vh]" // Added object-contain and max-height for mobile
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              />
             
            </div>
            <div className='w-1/2 flex flex-col items-center self-center sm:w-full lg:w-full lg:text-center'>
              <AnimatedText text="Decoding Data. Driving Decisions. Delivering Impact."
                className='!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-4xl md:!text-3xl sm:!2xl' />
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>Hi, I&apos;m Renu Deshmukh — a passionate Data Analyst with a strong foundation in turning data into meaningful insights.
I specialize in Power BI, SQL, Python, and also bring hands-on experience in ASP.NET, C#, MVC, and React.

With a keen interest in data storytelling and problem-solving, I thrive on learning new tools and technologies. I’m always excited to contribute my skills to innovative and impactful projects that drive real business value.

 </p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href="/RenuResume.pdf" target='_blank'
                  className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg 
                  text-lg font-semibold hover:bg-light hover:text-dark border-2 border-soild 
                  border-transparent hover:border-dark lg:items md:p-2 md:px-4 md:text-base'
                  download={true} >Resume<LinkArrow className={'w-6 ml-1'} />
                </Link>
                <Link href="/contacts"
                  className='ml-4 text-lg font-medium capitalize text-dark underline md:text-base'>
                  Contact ME</Link>

              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className='absolute right-8 bottom-8 inline-block w-14 md:hidden'>
          <Image src={lightbulb} alt="Renu" className='w-full h-auto' />
        </div>
      </main >
    </>
  )
}
